"""Add legendary resistance and update skills format

Revision ID: e75cf71e1a77
Revises: 
Create Date: 2025-03-20 15:10:23.459720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75cf71e1a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legendary_resistance', sa.Integer(), nullable=True))
        batch_op.drop_column('mythic_actions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mythic_actions', sa.TEXT(), nullable=True))
        batch_op.drop_column('legendary_resistance')

    # ### end Alembic commands ###
